version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    environment:
      RAILS_ENV: development
  
  database:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - db_data:/app/db

volumes:
  gem_cache:
  db_data:
  node_modules: